version: "3"
services:
  jenkins:
    image: jenkins/jenkins
    hostname: jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    volumes:
      - /workspace/admhabits/docker/jenkins/config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
